# wandb
wandb_name: "gnn_mass"
# data
pth: "data/MassSpecGym.tsv"
candidates_pth: "data/MassSpecGym_retrieval_candidates_mass_with_test.json"
split_type: "benchmark"
# output
mz_max: 1005.
mz_bin_res: 0.01
ints_transform: "sqrt"
# model
model_type: "gnn"
# optimization
max_epochs: 100
# other
accelerator: "gpu"
save_ckpt: True