# wandb
wandb_name: "sim_gnn"
# data
pth: "data/MassSpecGym.tsv"
split_type: "benchmark"
# output
mz_max: 1005.
mz_bin_res: 0.01
ints_transform: "sqrt"
# model
model_type: "gnn"
# optimization
max_epochs: 100
# other
accelerator: "gpu"
do_retrieval: False